# Generated by Django 2.1.7 on 2019-02-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='lobby', max_length=50),
            preserve_default=False,
        ),
    ]
